# Python Floating-Point Precision

## Basic Data Precision
In Python, floating-point numbers follow the **double-precision (float64)** standard. This means:
- Floating-point numbers have approximately **16 decimal places of precision**.
- The range of values that can be represented is approximately **10⁻³⁰⁸ to 10³⁰⁸**.

# Representation of Matrix or Vetor

In [14]:
import numpy as np

a = np.array(
    [
        [1, 2.5, 3],
        [-1, -2, -1.5],
        [4, 5.5, 6]
    ]
) # matrix

b = np.array([7, 5, 3]) # vector

In [3]:
print(a)

[[ 1.   2.5  3. ]
 [-1.  -2.  -1.5]
 [ 4.   5.5  6. ]]


In [4]:
print(b)

[7 5 3]


# Size of matrix or Vector

In [5]:
print(a.shape)

(3, 3)


In [6]:
print(a.shape[0])
print(a.shape[1])

3
3


In [ ]:
print(b.shape) # Vector

(3,)


# Representation of Complex Matrix or Vector

In [9]:
a = np.array(
    [
        [1 - 2j, 3 + 1j, 1],
        [1 + 2j, 2-1j, 7]
    ]
)

b = np.array([1 + 8j, -2j])

In [ ]:
a = np.array(
    [
        [1 - 2j, 3 + 1j, 1],
        [1 + 2j, 2-j, 7] # 2 - 1j
    ]
)

NameError: name 'j' is not defined

# Access to Value of Matrix or Vector

In [11]:
a[1, 1] = 0
a

array([[1.-2.j, 3.+1.j, 1.+0.j],
       [1.+2.j, 0.+0.j, 7.+0.j]])

In [12]:
a[0][0] = 0
a

array([[0.+0.j, 3.+1.j, 1.+0.j],
       [1.+2.j, 0.+0.j, 7.+0.j]])

In [13]:
b[0] = 0
b

array([ 0.+0.j, -0.-2.j])

In [ ]:
a = np.array(
    [
        [1, 2.5, 3],
        [-1, -2, -1.5],
        [4, 5.5, 6]
    ]
) # dtype = np.float64

b = np.array([7, 5, 3]) 

In [26]:
print(type(a[1, 1]))

<class 'numpy.float64'>


In [27]:
a[1, 1] = 0 + 0j

TypeError: can't convert complex to float

In [ ]:
a = np.array(
    [
        [1, 2.5, 3],
        [-1, -2, -1.5],
        [4, 5.5, 6]
    ],
    dtype = np.complex128
) # When creating matrices and vectors, make it a habit to use dtype.

In [30]:
a[1, 1] = 0 + 0j

In [31]:
a

array([[ 1. +0.j,  2.5+0.j,  3. +0.j],
       [-1. +0.j,  0. +0.j, -1.5+0.j],
       [ 4. +0.j,  5.5+0.j,  6. +0.j]])

# Explicit type conversion 

In [32]:
a = np.array(
    [
        [1, 2.5, 3],
        [-1, -2, -1.5],
        [4, 5.5, 6]
    ],
    dtype = np.float64
) 

In [33]:
a[1, 1] = 0 + 0j

TypeError: can't convert complex to float

In [34]:
a = a.astype(dtype = np.complex128)

In [35]:
a[1, 1] = 0 + 0j

In [36]:
a

array([[ 1. +0.j,  2.5+0.j,  3. +0.j],
       [-1. +0.j,  0. +0.j, -1.5+0.j],
       [ 4. +0.j,  5.5+0.j,  6. +0.j]])

In [37]:
a = a.astype(dtype = np.float64)

C:\Users\fkid0\AppData\Local\Temp\ipykernel_33208\2527551610.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  a = a.astype(dtype = np.float64)


In [38]:
a

array([[ 1. ,  2.5,  3. ],
       [-1. ,  0. , -1.5],
       [ 4. ,  5.5,  6. ]])

# Implicit type conversion

In [40]:
a = np.array(
    [
        [1, 2.5, 3],
        [-1, -2, -1.5],
        [4, 5.5, 6]
    ],
    dtype = np.float64
)

c = np.array(
    [
        [0, 1.5 - 1j, 2],
        [1, 2, -3.5],
        [0, 1.5, 7.5]
    ],
    dtype = np.complex128
)

In [41]:
d = a + c

In [42]:
print(type(d[1, 1]))

<class 'numpy.complex128'>


In [43]:
e = (1 + 0j) * a

In [44]:
print(type(e[1, 1]))

<class 'numpy.complex128'>
