In [1]:
import numpy as np

## 1. Identity Matrix: `numpy.eye()` / `numpy.identity()`
### `numpy.eye(N, M=None, k=0, dtype=float, order='C')`
- Generates an **identity matrix** (a square matrix with ones on the main diagonal and zeros elsewhere).
- `N × M` defines the matrix size; if `M` is `None`, it defaults to `N` (square matrix).
- The parameter `k` shifts the diagonal:
  - `k > 0`: Moves the diagonal **up**.
  - `k < 0`: Moves the diagonal **down**.

### `numpy.identity(n, dtype=float)`
- Generates an **identity matrix** of size `n × n`.
- Similar to `numpy.eye()`, but only supports square matrices.

In [3]:
a1 = np.eye(3, 4, k = 0, dtype= np.float64)

In [4]:
print(a1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [5]:
a2 = np.eye(4, 3, k = 1, dtype=np.complex128)

In [7]:
print(a2)

[[0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


In [9]:
a3 = np.identity(3)

In [10]:
print(a3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
a3 = np.eye(3, 3)

In [14]:
print(a3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
a3 = np.eye(3)

In [16]:
print(a3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 2. Triangular Matrix: `numpy.tri()`
### `numpy.tri(N, M=None, k=0, dtype=float)`
- Generates a **lower triangular matrix**, where elements **below the main diagonal** are `1`, and the rest are `0`.
- The parameter `k` shifts the diagonal:
  - `k > 0`: Moves the diagonal **up**.
  - `k < 0`: Moves the diagonal **down**.

In [17]:
t1 = np.tri(4, 3, k = 0)

In [18]:
print(t1)

[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [19]:
t2 = np.tri(4, 3, k =-1)

In [20]:
print(t2)

[[0. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]


In [21]:
t3 = np.tri(4)

In [22]:
print(t3)

[[1. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 1. 0.]
 [1. 1. 1. 1.]]


## 3. Predefined Arrays: `numpy.zeros()`, `numpy.ones()`, `numpy.full()`
### `numpy.zeros(shape, dtype=float, order='C')`
- Creates an array of the given shape, filled with **zeros**.

### `numpy.ones(shape, dtype=float, order='C')`
- Creates an array of the given shape, filled with **ones**.

### `numpy.full(shape, fill_value, dtype=None, order='C')`
- Creates an array of the given shape, filled with a **specified value** (`fill_value`).

In [ ]:
sh = (2, 3)

zr1 = np.zeros(sh, dtype=np.float64)

In [ ]:
print(zr1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [25]:
zr2 = np.zeros(sh, dtype=np.complex128)

In [26]:
print(zr2)

[[0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j]]


In [27]:
on1 = np.ones(sh, dtype=np.float64)

In [28]:
print(on1)

[[1. 1. 1.]
 [1. 1. 1.]]


In [29]:
on2 = np.ones(sh, dtype=np.complex128)

In [30]:
print(on2)

[[1.+0.j 1.+0.j 1.+0.j]
 [1.+0.j 1.+0.j 1.+0.j]]


In [ ]:
fulla1 = np.full(sh, 5, dtype=np.float64)

In [ ]:
print(fulla1)

[[5. 5. 5.]
 [5. 5. 5.]]


In [34]:
fulla2 = np.full(sh, 5+5j, dtype=np.complex128)

In [35]:
print(fulla2)

[[5.+5.j 5.+5.j 5.+5.j]
 [5.+5.j 5.+5.j 5.+5.j]]


## 4. Random Matrix: `numpy.random.rand()`
### `numpy.random.rand(d0, d1, ..., dn)`
- Generates an array of given shape with **random values** sampled from a uniform distribution in the range `[0, 1)`.
- Supports **multi-dimensional arrays**.

In [36]:
rand_a = np.random.rand(3, 5)

In [37]:
print(rand_a)

[[0.48606681 0.55662077 0.19054822 0.52555526 0.00157932]
 [0.68986126 0.34682438 0.49596624 0.19368342 0.13533727]
 [0.04743508 0.12601524 0.74586634 0.1231233  0.95481608]]


In [38]:
rand_a = np.random.rand(3, 5)

In [39]:
print(rand_a)

[[0.02367762 0.5486815  0.75207155 0.84536281 0.02504027]
 [0.63805079 0.79386032 0.62005152 0.35959056 0.99542266]
 [0.90866092 0.11080102 0.12593733 0.93320143 0.55631418]]
