In [2]:
import numpy as np

## 1. Copying Arrays: `np.copy()`
### `numpy.copy(a, order='K')`
- Returns a **copy of the given array**.
- The copy is **independent** of the original array (modifications do not affect the original).
- The `order` parameter controls memory layout (`'C'` for row-major, `'F'` for column-major, `'K'` to match the original layout).

- **Without `np.copy()`, arrays may share the same memory location**. This means:
  - If you assign an array to a new variable without copying (`B = A`), both `A` and `B` point to the same memory location.
  - Modifying `B` will also modify `A` (since they reference the same object).
  - Using `np.copy(A)` ensures `B` has a separate memory allocation, preventing unintended side effects.

In [13]:
m = [
    [1, 2.5, 3],
    [-1, -2, -1.5],
    [4, 5.5, 6]
]

In [3]:
a = np.array(m, dtype=np.float64)

In [4]:
print(a)

[[ 1.   2.5  3. ]
 [-1.  -2.  -1.5]
 [ 4.   5.5  6. ]]


In [5]:
b = a

In [6]:
print(b)

[[ 1.   2.5  3. ]
 [-1.  -2.  -1.5]
 [ 4.   5.5  6. ]]


In [7]:
a[0, 0] = 2

In [8]:
print(a)

[[ 2.   2.5  3. ]
 [-1.  -2.  -1.5]
 [ 4.   5.5  6. ]]


In [ ]:
print(b) 

[[ 2.   2.5  3. ]
 [-1.  -2.  -1.5]
 [ 4.   5.5  6. ]]


In [14]:
b_copy = np.copy(a)

In [15]:
a[0, 0] = 3

In [16]:
print(a)

[[ 3.   2.5  3. ]
 [-1.   3.  -1.5]
 [ 4.   5.5  6. ]]


In [17]:
print(b)

[[ 3.   2.5  3. ]
 [-1.   3.  -1.5]
 [ 4.   5.5  6. ]]


In [18]:
print(b_copy)

[[ 2.   2.5  3. ]
 [-1.   3.  -1.5]
 [ 4.   5.5  6. ]]


## 2. Reshaping Arrays: `np.reshape()`
### `numpy.reshape(a, newshape, order='C')`
- Returns a **reshaped view** of the original array (if possible).
- `newshape` defines the target shape and must be **compatible with the original number of elements**.
  - The total number of elements in the original array must be **equal** to the total number of elements in the reshaped array.
- The `order` parameter determines whether elements are read in **row-major (`'C'`)** or **column-major (`'F'`)** order.

- **Reshaped arrays share memory with the original array**, meaning:
  - If `B = A.reshape(...)` is used, `B` and `A` share the same data.
  - Modifying `B` will also affect `A`, since they reference the same memory.

In [28]:
m = [
    [1, 2.5, 3],
    [-1, -2, -1.5]
]

In [29]:
a = np.array(m, dtype=np.float64)

In [30]:
print(a)

[[ 1.   2.5  3. ]
 [-1.  -2.  -1.5]]


In [32]:
b = np.reshape(a, 6)

In [33]:
print(b)

[ 1.   2.5  3.  -1.  -2.  -1.5]


In [34]:
a[0, 0] = 0

In [35]:
print(b)

[ 0.   2.5  3.  -1.  -2.  -1.5]


In [36]:
b = np.reshape(a, (3, 2))

In [37]:
print(b)

[[ 0.   2.5]
 [ 3.  -1. ]
 [-2.  -1.5]]


## 3. Lower and Upper Triangular Matrices: `np.tril()` / `np.triu()`
### `numpy.tril(m, k=0)`
- Returns the **lower triangular part** of a matrix, setting elements above the diagonal to `0`.
- The `k` parameter shifts the diagonal:
  - `k > 0`: Includes more upper diagonal elements.
  - `k < 0`: Excludes more lower diagonal elements.

### `numpy.triu(m, k=0)`
- Returns the **upper triangular part** of a matrix, setting elements below the diagonal to `0`.
- The `k` parameter shifts the diagonal:
  - `k > 0`: Excludes more lower diagonal elements.
  - `k < 0`: Includes more upper diagonal elements.

- **Unlike `np.reshape()`, `np.tril()` and `np.triu()` return a new array with a separate memory allocation**.  
  - Modifications made to the output of `np.tril()` or `np.triu()` **do not affect the original array**.

In [82]:
m1 = [
    [1, 2.5, 3],
    [-1, -2, -1.5],
    [4, 5.5, 6]
]

In [75]:
a1 = np.array(m1, dtype=np.float64)

In [57]:
b1_low = np.tril(a1)

In [58]:
print(b1_low)

[[ 1.   0.   0. ]
 [-1.  -2.   0. ]
 [ 4.   5.5  6. ]]


In [59]:
b1_up = np.triu(a1)

In [62]:
print(b1_low)

[[ 1.   0.   0. ]
 [-1.  -2.   0. ]
 [ 4.   5.5  6. ]]


In [78]:
a1[0,0] = 0

In [64]:
print(b1_low)

[[ 1.   0.   0. ]
 [-1.  -2.   0. ]
 [ 4.   5.5  6. ]]


In [84]:
b1_low = np.tril(a1, k =1)

In [85]:
print(b1_low)

[[ 0.   2.5  0. ]
 [-1.  -2.  -1.5]
 [ 4.   5.5  6. ]]


In [83]:
m2 = [
    [1, 2.5, 3],
    [-1, -2, -1.5]
]

In [66]:
a2 = np.array(m2, dtype=np.float64)

In [67]:
b2_low = np.tril(a2)

In [68]:
print(b2_low)

[[ 1.  0.  0.]
 [-1. -2.  0.]]


In [69]:
b2_up = np.triu(a2)

In [70]:
print(b2_up)

[[ 1.   2.5  3. ]
 [ 0.  -2.  -1.5]]


## 4. Extracting and Constructing Diagonals: `np.diag()`
### `numpy.diag(v, k=0)`
- If `v` is a **1D array**, returns a **diagonal matrix** with `v` as the main diagonal.
- If `v` is a **2D array**, returns the **diagonal elements** of `v`.
- The `k` parameter shifts the diagonal:
  - `k > 0`: Extracts diagonals above the main diagonal.
  - `k < 0`: Extracts diagonals below the main diagonal.


- **If `v` is a 2D array, the extracted diagonal shares memory with the original array**:
  - Modifying the extracted diagonal may affect the original matrix.
  - To avoid this, use `np.copy(np.diag(A))` to create an independent copy.

In [86]:
print(a)

[[ 0.   2.5  3. ]
 [-1.  -2.  -1.5]]


In [87]:
b = np.diag(a)

In [88]:
print(b)

[ 0. -2.]


In [89]:
a[0,0] = 3

In [90]:
print(b)

[ 3. -2.]


In [91]:
b[0] = 3

ValueError: assignment destination is read-only

In [92]:
b = np.diag(a, k = 1)

In [93]:
print(b)

[ 2.5 -1.5]


- **If `v` is a 1D array, `np.diag(v)` generates a square matrix where `v` is placed on the specified diagonal**:
  - The output matrix has a size of `(len(v), len(v))`, with zeros elsewhere.
  - **This new matrix is allocated in a separate memory space, meaning modifications to it do not affect the original array.**

In [95]:
a = np.array([1, 2, 3, 4], dtype=np.float64)

In [96]:
b = np.diag(a)

In [97]:
print(b)

[[1. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]


In [98]:
b = np.diag(a, k = -1)

In [99]:
print(b)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [100]:
a[0] = 0

In [102]:
print(a)

[0. 2. 3. 4.]


In [101]:
print(b)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


## 5. Creating Diagonal Matrices from Flattened Arrays: `np.diagflat()`
### `numpy.diagflat(v, k=0)`
- Creates a **diagonal matrix** from a **flattened input array**.
- Similar to `np.diag()`, but ensures the input is treated as a **1D flattened array** before constructing the diagonal.

In [103]:
print(a)

[0. 2. 3. 4.]


In [104]:
b = np.diagflat(a)

In [105]:
print(b)

[[0. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]


In [106]:
b = np.diagflat(a, k = 1)

In [107]:
print(b)

[[0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 3. 0.]
 [0. 0. 0. 0. 4.]
 [0. 0. 0. 0. 0.]]


In [108]:
a = np.array([
    [1, 3],
    [2, 4]
], dtype=np.float64)

In [109]:
b = np.diagflat(a)

In [111]:
print(b)

[[1. 0. 0. 0.]
 [0. 3. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 4.]]


## 6. Computing the Trace of a Matrix: `np.trace()`
### `numpy.trace(a, offset=0, axis1=0, axis2=1, dtype=None, out=None)`
- Returns the **sum of the diagonal elements** of a matrix.
- The `offset` parameter shifts the diagonal:
  - `offset > 0`: Uses an upper diagonal.
  - `offset < 0`: Uses a lower diagonal.
- `axis1` and `axis2` specify which dimensions to consider as rows and columns in higher-dimensional arrays.

In [113]:
a = np.array(m1, dtype=np.float64)

In [114]:
print(a)

[[ 1.   2.5  3. ]
 [-1.  -2.  -1.5]
 [ 4.   5.5  6. ]]


In [115]:
b = np.trace(a)

In [116]:
print(b)

5.0


In [117]:
b = np.trace(a, offset=1)

In [118]:
print(b)

1.0


## 7. Flattening Arrays: `flatten()` / `np.ravel()`
### `array.flatten(order='C')`
- Returns a **copy** of the array, flattened into a 1D array.
- The `order` parameter determines the read order:
  - `'C'`: Row-major order.
  - `'F'`: Column-major order.

### `numpy.ravel(a, order='C')`
- Returns a **flattened view** of the array, if possible.
- Unlike `flatten()`, it **does not necessarily return a copy** (modifications may affect the original array).

In [119]:
print(a)

[[ 1.   2.5  3. ]
 [-1.  -2.  -1.5]
 [ 4.   5.5  6. ]]


In [122]:
b_flat = a.flatten()

In [123]:
print(b_flat)

[ 1.   2.5  3.  -1.  -2.  -1.5  4.   5.5  6. ]


In [124]:
b_ravel = np.ravel(a)

In [125]:
print(b_ravel)

[ 1.   2.5  3.  -1.  -2.  -1.5  4.   5.5  6. ]


In [126]:
a[0, 0] = 0

In [127]:
print(b_flat)

[ 1.   2.5  3.  -1.  -2.  -1.5  4.   5.5  6. ]


In [128]:
print(b_ravel)

[ 0.   2.5  3.  -1.  -2.  -1.5  4.   5.5  6. ]
