In [1]:
import numpy as np

## 1. np.hstack / np.vstack
- `np.hstack`: Horizontally stacks arrays (requires the same number of rows).
- `np.vstack`: Vertically stacks arrays (requires the same number of columns).

In [4]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
], dtype = np.float64)

b = np.array([
    [-1, -2],
    [-3, -4]
], dtype = np.float64)

In [5]:
hmat = np.hstack((a, b))

In [6]:
print(hmat)

[[ 1.  2.  3. -1. -2.]
 [ 4.  5.  6. -3. -4.]]


In [7]:
vmat = np.vstack((a, b))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [8]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
], dtype=np.float64)

b = np.array([
    [-1, -2, -3],
    [-4, -5, -6],
    [-7, -8, -9]
], dtype = np.float64)

In [9]:
vmat = np.vstack((a, b))

In [10]:
print(vmat)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [-1. -2. -3.]
 [-4. -5. -6.]
 [-7. -8. -9.]]


In [11]:
hmat = np.hstack((a, b))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 3

In [12]:
a = np.array([1, 2, 3], dtype = np.float64)
b = np.array([4, 5, 6], dtype = np.float64)

In [13]:
hmat = np.hstack((a, b))
vmat = np.vstack((a, b))

In [14]:
print(hmat)

[1. 2. 3. 4. 5. 6.]


In [15]:
print(vmat)

[[1. 2. 3.]
 [4. 5. 6.]]


In [16]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
], dtype = np.float64)

b = np.array([7, 8, 9], dtype = np.float64)

In [17]:
vmat = np.vstack((a, b))

In [18]:
print(vmat)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [19]:
hmat = np.hstack((a, b))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

## 2. Transpose
- The `transpose()` method or `.T` attribute flips the axes of an array.
- Converts rows to columns and vice versa.
- Transposed arrays share the same memory as the original array (modifying one affects the other).


In [20]:
a = np.array([
    [1, 2, 3], 
    [4, 5, 6],
    [7, 8, 9]
], dtype = np.float64)

b = a.transpose()

In [21]:
print(b)

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [22]:
b = a.T

In [23]:
print(b)

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [24]:
a[0,0] = 100

In [25]:
print(b)

[[100.   4.   7.]
 [  2.   5.   8.]
 [  3.   6.   9.]]


## 3. Real Property / Imag Property / Conjugate Method
- `.real`: Extracts the real part of a complex number (shares memory with the original array).
- `.imag`: Extracts the imaginary part of a complex number (shares memory with the original array).
- `.conjugate()`: Returns the complex conjugate (creates a new array, does not share memory).

In [26]:
a = np.array([
    [1 - 2j, 3 + 1j, 1],
    [1 + 2j, 2 - 1j, 7]
], dtype = np.complex128)

In [32]:
a_real = a.real
a_imag = a.imag
a_conj = a.conjugate()

In [29]:
print(a_real)

[[1. 3. 1.]
 [1. 2. 7.]]


In [30]:
print(a_imag)

[[-2.  1.  0.]
 [ 2. -1.  0.]]


In [33]:
print(a_conj)

[[1.+2.j 3.-1.j 1.-0.j]
 [1.-2.j 2.+1.j 7.-0.j]]


In [34]:
a[0,0] = 100 + 101j

In [35]:
print(a_real)

[[100.   3.   1.]
 [  1.   2.   7.]]


In [36]:
print(a_imag)

[[101.   1.   0.]
 [  2.  -1.   0.]]


In [37]:
print(a_conj)

[[1.+2.j 3.-1.j 1.-0.j]
 [1.-2.j 2.+1.j 7.-0.j]]


## 4. Matrix Multiplication: np.matmul, @, Scalar Multiplication
- `np.matmul(A, B)`: Performs matrix multiplication.
- `A @ B`: Equivalent to `np.matmul(A, B)`, used for matrix multiplication.
- `scalar * A`: Multiplies each element of matrix `A` by the scalar.

In [38]:
# scalar * matrix
A = np.array([
    [1, 2, 1],
    [2, 1, 3],
    [1, 3, 1]
], dtype = np.float64)

r = 5.0

In [39]:
rA = r * A

In [40]:
print(rA)

[[ 5. 10.  5.]
 [10.  5. 15.]
 [ 5. 15.  5.]]


In [41]:
rA = A * r

In [42]:
print(rA)

[[ 5. 10.  5.]
 [10.  5. 15.]
 [ 5. 15.  5.]]


In [43]:
# matrix * matrix
A = np.array([
    [1, 2, 1],
    [3, 2, 1]
], dtype = np.float64)

B = np.array([
    [2, 1],
    [1, 2],
    [-3, 3]
], dtype = np.float64)

In [45]:
AB = A @ B

In [46]:
print(AB)

[[ 1.  8.]
 [ 5. 10.]]


In [47]:
AB = np.matmul(A, B)

In [48]:
print(AB)

[[ 1.  8.]
 [ 5. 10.]]


In [49]:
BA = B @ A

In [50]:
print(BA)

[[5. 6. 3.]
 [7. 6. 3.]
 [6. 0. 0.]]


In [52]:
# matrix * vector
A = np.array([
    [1, 2, 1],
    [2, 1, 3],
    [1, 3, 1]
], dtype = np.float64)

u = np.array([5, 1, 2], dtype = np.float64)

In [ ]:
Au = A @ u

In [54]:
print(Au)

[ 9. 17. 10.]


## 5. Inner Product: np.vdot, np.dot
- `np.vdot(A, B)`: Computes the dot product of two vectors, considering complex conjugates.
  - Unlike the conventional complex inner product, NumPy's `vdot` takes the conjugate of the first vector `u`.
- `np.dot(A, B)`: Computes the dot product of vectors or matrix multiplication.
  - For real numbers, `np.dot` is the same as `np.vdot`.
  - For complex numbers, `np.dot` does not take the conjugate, unlike `np.vdot`.

In [55]:
u = np.array([1 + 2j, 3 + 4j], dtype = np.complex128)
v = np.array([5 + 6j, 7 + 8j], dtype = np.complex128)

In [57]:
vdot = np.vdot(u, v)
dot = np.dot(u, v)

In [58]:
print(vdot)
print(dot)

(70-8j)
(-18+68j)


## 6. Norm Calculation 
- `np.linalg.norm(A)`: Computes the Frobenius norm (default) of a matrix or the Euclidean norm of a vector.
- `np.linalg.norm(A, ord=1)`: Computes the 1-norm (sum of absolute column sums).
- `np.linalg.norm(A, ord=np.inf)`: Computes the infinity norm (maximum absolute row sum).
- `np.linalg.norm(A, ord=2)`: Computes the spectral norm (largest singular value for matrices).

In [60]:
from scipy import linalg

In [59]:
A = np.array([
    [3, 4],
    [1, 2]
], dtype = np.float64)

In [61]:
frobenius_norm = linalg.norm(A)
one_norm = linalg.norm(A, ord=1) 
inf_norm = linalg.norm(A, ord=np.inf)
euclidean_norm = linalg.norm(A[0])

In [63]:
print(frobenius_norm)
print(one_norm)
print(inf_norm)
print(euclidean_norm)

5.477225575051661
6.0
7.0
5.0


## 7. Extracting Parts of a Matrix or Vector `[:, :]`
- `A[i, j]`: Extracts a specific element.
- `A[:, j]`: Extracts a specific column.
- `A[i, :]`: Extracts a specific row.
- `A[start:end, start:end]`: Extracts a submatrix.

- `A[1:2, 1:4]`: Extracts a 2D submatrix with shape `(1,3)`.
- `A[1, 1:4]`: Extracts a 1D row vector with shape `(3,)`.
- `A[1:, 1:2]`: Extracts a 2D column submatrix with shape `(3,1)`.
- `A[1:, 1]`: Extracts a 1D column vector with shape `(3,)`.
- To reshape a 1D vector into a 2D array, use `np.reshape(A, (m, n))`.

In [64]:
A = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [-1, -2, -3, -4, -5]
], dtype = np.float64)

In [65]:
sub_A = A[1:3, 1:4]

In [66]:
print(sub_A)

[[ 7.  8.  9.]
 [12. 13. 14.]]


In [67]:
sub_A = A[2:, 1:4]

In [68]:
print(sub_A)

[[12. 13. 14.]
 [-2. -3. -4.]]


In [69]:
sub_A = A[:, 1:4]

In [70]:
print(sub_A)

[[ 2.  3.  4.]
 [ 7.  8.  9.]
 [12. 13. 14.]
 [-2. -3. -4.]]


In [71]:
sub_A = A[:, :]

In [72]:
print(sub_A)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [-1. -2. -3. -4. -5.]]


In [73]:
sub_A = A[1:2, :]

In [74]:
print(sub_A)

[[ 6.  7.  8.  9. 10.]]


In [75]:
print(sub_A.shape)

(1, 5)


In [76]:
sub_A = A[1, :]

In [77]:
print(sub_A)

[ 6.  7.  8.  9. 10.]


In [78]:
print(sub_A.shape)

(5,)


In [80]:
sub_A1 = A[1:2, :]
sub_A2 = A[1, :]

In [86]:
reshaped_sub_A1 = sub_A1.reshape(5, )

In [87]:
print(reshaped_sub_A1.shape)

(5,)


In [84]:
reshaped_sub_A2 = sub_A1.reshape(1, 5)

In [89]:
print(reshaped_sub_A2.shape)

(1, 5)
