In [1]:
import numpy as np

## 1. Addition and Subtraction of Matrices  
- Matrices must have the same shape to be added or subtracted.  
- The operation is performed element-wise, meaning each corresponding element from both matrices is added or subtracted.  

In [2]:
b1 = (-1) * np.ones((4, ), dtype = np.float64)
b2 = 2 * np.ones((5, ), dtype = np.float64)
b3 = np.ones((4, ), dtype = np.float64)

In [5]:
A = np.diag(b1, k = -1) + np.diag(b2) + np.diag(b3, k = 1)

In [6]:
print(A)

[[ 2.  1.  0.  0.  0.]
 [-1.  2.  1.  0.  0.]
 [ 0. -1.  2.  1.  0.]
 [ 0.  0. -1.  2.  1.]
 [ 0.  0.  0. -1.  2.]]


## 2. Scalar Addition to a Matrix  
- When a scalar is added to a matrix, it is broadcasted to every element in the matrix.  
- This means each entry of the matrix is increased by the scalar value.  

In [8]:
A = np.array([
    [1, 2],
    [3, 4]
], dtype = np.float64)

r = 5

In [9]:
result= A + r

In [10]:
print(result)

[[6. 7.]
 [8. 9.]]


In [11]:
print(r + A)

[[6. 7.]
 [8. 9.]]


## 3. Element-wise Multiplication (A * B)  
- When using `*` between two matrices, NumPy performs element-wise multiplication.  
- This means each corresponding element in matrices A and B is multiplied together.  
- This is different from matrix multiplication (`np.matmul` or `@`), which follows linear algebra rules.  

In [14]:
A = np.array([
    [1, 2],
    [3, 4]
], dtype = np.float64)

B = np.array([
    [5, 6],
    [7, 8]
], dtype = np.float64)

In [15]:
C = A * B

In [16]:
print(C)

[[ 5. 12.]
 [21. 32.]]


In [17]:
C = A / B

In [19]:
print(C)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [20]:
C = B / A

In [21]:
print(C)

[[5.         3.        ]
 [2.33333333 2.        ]]


## 4. Matrix-Vector Multiplication (A * b)  
- If A is a matrix and b is a vector, `A * b` applies element-wise multiplication if their shapes align.  
- The number of columns in A must match the size of b for this operation to work.  
- This is different from the traditional matrix-vector multiplication (`np.matmul(A, b)`), which performs a dot product.  

In [22]:
A = np.array([
    [1, 2],
    [3, 4]
], dtype = np.float64)

b = np.array([2, 4], dtype=np.float64)

In [23]:
C = A * b

In [24]:
print(C)

[[ 2.  8.]
 [ 6. 16.]]


- Additionally, `1 / A` performs element-wise inversion, meaning each entry of A is replaced by its reciprocal.  
- **This is not the same as the inverse of a matrix (`np.linalg.inv(A)`)**, which follows a different mathematical operation based on linear algebra.

In [25]:
# b/A -> b * 1 / A
C = b * 1 / A 

In [27]:
print(C)

[[2.         2.        ]
 [0.66666667 1.        ]]


## 5. Indexing Rows or Columns  
- Specific rows or columns of a matrix can be selected using indexing.  
- This allows the creation of a new matrix by extracting only certain rows or columns.  
- Example: `A[:, 1]` selects the second column, and `A[0, :]` selects the first row.  

In [33]:
A = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [-1, -2, -3, -4, -5]
], dtype = np.float64)

In [35]:
idx = [1, 2, 0, 3]
result = A[idx, :]

In [36]:
print(result)

[[ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [ 1.  2.  3.  4.  5.]
 [-1. -2. -3. -4. -5.]]


In [38]:
idx_r = [2, 3, 0]
idx_c = [2, 1, 3]

result = A[idx_r, :][: ,idx_c]

In [39]:
print(result)

[[13. 12. 14.]
 [-3. -2. -4.]
 [ 3.  2.  4.]]
