In [3]:
from scipy import linalg
import numpy as np

#  Determinant

-> LU Decomposition

In [4]:
A1 = np.array([
    [1, 5, 0],
    [2, 4, -1],
    [0, -2, 0]
], dtype = np.float64)

A2 = np.array([
    [1, -4, 2],
    [-2, 8, -9],
    [-1, 7, 0]
], dtype = np.float64)

In [5]:
det_A1 = linalg.det(A1)
det_A2 = linalg.det(A2)

In [6]:
print(det_A1)
print(det_A2)

-2.0
15.0


# Inverse Matrix

In [7]:
A = np.array([
    [1, 2, 1],
    [2, 1, 3],
    [1, 3, 1]
], dtype = np.float64)

In [8]:
inv_A = linalg.inv(A)

In [9]:
print(inv_A)

[[ 8. -1. -5.]
 [-1.  0.  1.]
 [-5.  1.  3.]]


# Calculating Ax = b

In [39]:
b = np.array([1, 1, 1], dtype = np.float64)

A_sing = np.array([
    [1, 3, 4],
    [-4, 2, -6],
    [-3, -2, -7]
], dtype = np.float64)

A_gen = np.array([
    [0, 1, 2],
    [1, 0, 3],
    [4, -3, 8]
], dtype = np.float64)

A_sym = np.array([
    [1, 2, 1],
    [2, 1, 3],
    [1, 3, 1]
], dtype = np.float64)

A_sym_c = np.array([
    [1, 2 - 1j, 1 + 2j],
    [2 - 1j, 1, 3],
    [1 + 2j, 3, 1]
], dtype = np.complex128)

A_her = np.array([
    [1, 2 + 1j, 1 - 2j],
    [2 - 1j, 1, 3],
    [1 + 2j, 3, 1]
], dtype = np.complex128)

A_pos = np.array([
    [2, -1, 0],
    [-1, 2, -1],
    [0, -1, 2]
], dtype = np.float64)

In [18]:
x = linalg.solve(A_sing, b)

LinAlgError: Matrix is singular.

In [19]:
x = linalg.solve(A_gen, b)

In [20]:
print(x)

[ 1.  1. -0.]


In [23]:
x = linalg.solve(A_sym, b)

In [24]:
print(x)

[ 2.0000000e+00  4.4408921e-17 -1.0000000e+00]


In [25]:
x = linalg.solve(A_sym, b, assume_a = "sym")

In [26]:
print(x)

[ 2.  0. -1.]


In [28]:
x = linalg.solve(A_sym_c, b, assume_a="sym")

In [29]:
print(x)

[0.00689655+0.11724138j 0.35172414-0.02068966j 0.17241379-0.06896552j]


In [36]:
x = linalg.solve(A_her, b, assume_a = "her")

In [37]:
print(x)

[0.11111111+1.11111111e-01j 0.33333333-1.11111111e-01j
 0.11111111+1.11022302e-16j]


In [40]:
x = linalg.solve(A_pos, b, assume_a = "pos")

In [41]:
print(x)

[1.5 2.  1.5]


# Triangular Matrix Ax = b

In [42]:
b = np.array([1, 2, 3, 4], dtype = np.float64)

A = np.array([
    [1, 0, 0, 0],
    [1, 4, 0, 0],
    [5, 0, 1, 0],
    [8, 1, -2, 2]
], dtype = np.float64)

In [43]:
x = linalg.solve_triangular(A, b, lower = True)

In [44]:
print(x)

[ 1.     0.25  -2.    -4.125]


In [45]:
print(A @ x - b)

[0. 0. 0. 0.]


# 구한 해가 정확한가?

-> Ax와 b가 충분히 비슷한가?

-> Ax - b가 충분히 작은가? 0에 가까운가?

In [59]:
b = np.ones((3, ), dtype = np.float64)

A_pos = np.array([
    [2, -1, 0],
    [-1, 2, -1],
    [0, -1, 2]
], dtype = np.float64)

In [60]:
x = linalg.solve(A_pos, b, assume_a = "pos")

In [61]:
zr = np.zeros((3, ), dtype = np.float64)

In [62]:
bool_close = np.allclose(A_pos @ x - b, zr)

In [63]:
print(bool_close)

True
